name: Telegram Bot

on:
  schedule:
   - cron: '*/5 * * * *'

  workflow_dispatch:

# Налаштування обмеження одночасних запусків   
concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:

  setup:
  
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3

  run-bot:

    needs: setup
    
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Install requirements  
      run: pip install pyTelegramBotAPI==4.8.0
      
    - name: Stop previous bot
      run: |
        bot_pid=$(pgrep -af "python bot.py")
        if [ -n "$bot_pid" ]; then
          kill -9 $bot_pid
        fi

    - name: Run bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}  
      run: python bot.py
